language: objective-c
osx_image: xcode9.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
  - COMMAND="test-iOS"
  - COMMAND="test-native"
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- swift -version
- sh build.sh "$COMMAND"
