version: 2.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

commands:
  test_and_store_results:
    description: "Builds and tests the project and then stores the results of the tests as artifacts and test results report"
    steps:
      - checkout
      - run:
          name: test iOS
          command: fastlane scan
          environment:
              SCAN_PROJECT: "Lift.xcodeproj"
              SCAN_SCHEME: "Lift"
              SCAN_DEVICE: "iPhone Xs"
      - store_artifacts: # This will by default store an html and junit file as artifacts (See "Artifacts" tab in CircleCI report)
          path: test_output # test_output is the default temporary folder for fastlane scan output
          destination: test_output # This will create a sub structure in the artifacts section in CircleCI
      - store_test_results: # This will store the test results so you can then see them in the "Test Summary" tab in CircleCI report
          path: test_output

jobs:      
  test-xcode13-ios15:
    macos:
      xcode: "13.0.0"
    steps:
      - test_and_store_results

  test-xcode14-ios16:
    macos:
      xcode: "14.0.0"
    steps:
      - test_and_store_results

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - test-xcode13-ios15
      - test-xcode14-ios16