version: 2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
jobs:
  test-iOS:
    #working_directory: /Users/distiller/project
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            sh build.sh test-iOS

  test-native:
    #working_directory: /Users/distiller/project
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: test native
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            sh build.sh test-native

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-iOS
      - test-native
