version: 2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

jobs:
  test-xcode10-ios12:
    macos:
      xcode: "10.3.0"
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            fastlane test

  test-xcode11-ios13:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            fastlane test

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-xcode10-ios12
      - test-xcode11-ios13
